spring.application.name=precious-metals

management.endpoints.web.exposure.include=health,info,prometheus
management.observations.annotations.enabled=true
management.observations.key-values.application=${spring.application.name}

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
