/**
 * @typedef {"IS_EQUAL" | "IS_NOT_EQUAL" | "GREATER_THAN_EQUAL" | "GREATER_THAN" | "LESS_THAN" | "LESS_THAN_EQUAL"} Operator
 */
export const Operator = {
    IS_EQUAL: 'IS_EQUAL',
    IS_NOT_EQUAL: 'IS_NOT_EQUAL',
    GREATER_THAN_EQUAL: 'GREATER_THAN_EQUAL',
    GREATER_THAN: 'GREATER_THAN',
    LESS_THAN: 'LESS_THAN',
    LESS_THAN_EQUAL: 'LESS_THAN_EQUAL'
};
